struct CameraUniform {
    view_proj: mat4x4<f32>,
};
@group(0) @binding(0) var<uniform> u_camera: CameraUniform;

struct PackedVertex {
    pos_norm: u32,
    data: u32,
};

// We access the buffer generated by Compute Shader as ReadOnly here
@group(0) @binding(1) var<storage, read> vertex_pool: array<PackedVertex>;
    
struct VertexOutput {
    @builtin(position) clip_position: vec4<f32>,
    @location(0) norm: vec3<f32>,
    @location(1) color: vec3<f32>,
};

const normal_data = array<vec3<f32>, 6>(
    vec3<f32>( 1.0,  0.0,  0.0), // +X
    vec3<f32>(-1.0,  0.0,  0.0), // -X
    vec3<f32>( 0.0,  1.0,  0.0), // +Y
    vec3<f32>( 0.0, -1.0,  0.0), // -Y
    vec3<f32>( 0.0,  0.0,  1.0), // +Z
    vec3<f32>( 0.0,  0.0, -1.0), // -Z
);

@vertex
fn vs_main(@builtin(vertex_index) v_idx: u32) -> VertexOutput {
    let packed = vertex_pool[v_idx];
    
    // Unpack Position (8 bits per axis)
    let lx = f32((packed.pos_norm >> 0u) & 0xFFu);
    let ly = f32((packed.pos_norm >> 8u) & 0xFFu);
    let lz = f32((packed.pos_norm >> 16u) & 0xFFu);
    let norm_id = (packed.pos_norm >> 24u) & 0xFFu;
    var normal = normal_data[norm_id];
    
    // Constraints: 6.25cm voxel size = 0.0625 meters
    let scale = 0.0625;
    let world_pos = vec3<f32>(lx, ly, lz) * scale;
    
    
    // Material Coloring
    let mat_id = packed.data; // simplified
    var color = vec3<f32>(0.8, 0.8, 0.8);
    if (mat_id == 1u) { color = vec3<f32>(1.0, 0.2, 0.2); } // Red
    if (mat_id == 2u) { color = vec3<f32>(0.2, 1.0, 0.2); } // Green
    
    var out: VertexOutput;
    out.clip_position = u_camera.view_proj * vec4<f32>(world_pos, 1.0);
    out.norm = normal;
    out.color = color;
    return out;
}

@fragment
fn fs_main(in: VertexOutput) -> @location(0) vec4<f32> {
    // Simple lighting
    return vec4<f32>(in.color, 1.0);
}