const std = @import("std");
const math = std.math;
const linalg = @import("../linalg.zig");
const vec3 = linalg.vec3;
const vec3i = linalg.vec3i;
const vec2 = linalg.vec2;
const vec2i = linalg.vec2i;
const Allocator = std.mem.Allocator;
const ArrayList = std.array_list.Managed;



// --- Enums & Constants ---

pub const Mode = enum {
    CUBIC,
    POLYHEDRON,
    ROUNDED_POLYHEDRON,
    SEMI_ROUND,
    SPHERICAL,

    pub fn getMergeThreshold(self: Mode) f32 {
        return switch (self) {
            .CUBIC => 0.6,
            .POLYHEDRON => 1.3,
            .ROUNDED_POLYHEDRON => 2.1,
            .SEMI_ROUND => 5.0,
            .SPHERICAL => 20.0,
        };
    }
};

// --- Data Structures ---

const CellGeoData = struct {
    verts: ArrayList(vec3),
    uvs: ArrayList(vec2),
    uv2s: ArrayList(vec2),
    is_floor: ArrayList(bool), // Tracks smooth group (0 or -1)

    pub fn init(allocator: Allocator) CellGeoData {
        return .{
            .verts = ArrayList(vec3).init(allocator),
            .uvs = ArrayList(vec2).init(allocator),
            .uv2s = ArrayList(vec2).init(allocator),
            .is_floor = ArrayList(bool).init(allocator),
        };
    }

    pub fn deinit(self: *CellGeoData) void {
        self.verts.deinit();
        self.uvs.deinit();
        self.uv2s.deinit();
        self.is_floor.deinit();
    }
};

// --- Main Chunk Struct ---

pub const MarchingSquaresTerrainChunk = struct {
    allocator: Allocator,

    // -- Public Exports / Settings --
    chunk_coords: vec2i,
    merge_mode: Mode,
    merge_threshold: f32,
    dimensions: vec3i,
    cell_size: vec2,
    global_position: vec3,

    // -- Internal Storage --
    height_map: []f32, // Flattened 2D array [z * width + x]
    needs_update: []bool, // Flattened 2D array
    cell_geometry: []?CellGeoData, // Cache

    // -- Mesh Output Accumulators (SurfaceTool equivalents) --
    out_verts: ArrayList(vec3),
    out_uvs: ArrayList(vec2),
    out_uv2s: ArrayList(vec2),
    // Note: Normals and Indices are typically generated by SurfaceTool.commit().
    // We strictly output the geometry stream here.

    // -- Generation State --
    new_chunk: bool = false,
    higher_poly_floors: bool = true,
    current_cell_coords: vec2i,
    r: i32, // Rotation counter
    floor_mode: bool, // true = floor, false = wall

    // Heights of 4 corners
    ay: f32 = 0,
    by: f32 = 0,
    cy: f32 = 0,
    dy: f32 = 0,

    // Edge connected state
    ab: bool = false,
    ac: bool = false,
    bd: bool = false,
    cd: bool = false,

    cell_edges: [4]bool = undefined,
    point_heights: [4]f32 = undefined,

    const Self = @This();

    pub fn init(allocator: Allocator, dims: vec3i, c_size: vec2) !Self {
        const size = @as(usize, @intCast(dims[0] * dims[2]));

        // Allocate and initialize arrays
        const hm = try allocator.alloc(f32, size);
        @memset(hm, 0.0);

        const nu = try allocator.alloc(bool, size);
        @memset(nu, true); // All need update initially

        const cg = try allocator.alloc(?CellGeoData, size);
        @memset(cg, null);

        return Self{
            .allocator = allocator,
            .chunk_coords = vec2i.ZERO,
            .merge_mode = .POLYHEDRON,
            .merge_threshold = Mode.POLYHEDRON.getMergeThreshold(),
            .dimensions = dims,
            .cell_size = c_size,
            .global_position = .{ 0, 0, 0 },
            .height_map = hm,
            .needs_update = nu,
            .cell_geometry = cg,
            .out_verts = ArrayList(vec3).init(allocator),
            .out_uvs = ArrayList(vec2).init(allocator),
            .out_uv2s = ArrayList(vec2).init(allocator),
            .current_cell_coords = vec2i.ZERO,
            .r = 0,
            .floor_mode = true,
        };
    }

    pub fn deinit(self: *Self) void {
        self.allocator.free(self.height_map);
        self.allocator.free(self.needs_update);
        for (self.cell_geometry) |*geo| {
            if (geo.*) |*g| g.deinit();
        }
        self.allocator.free(self.cell_geometry);
        self.out_verts.deinit();
        self.out_uvs.deinit();
        self.out_uv2s.deinit();
    }

    pub fn set_merge_mode(self: *Self, mode: Mode) void {
        self.merge_mode = mode;
        self.merge_threshold = mode.getMergeThreshold();
        self.regenerate_all_cells();
    }

    pub fn regenerate_all_cells(self: *Self) void {
        var z: i32 = 0;
        while (z < self.dimensions[2] - 1) : (z += 1) {
            var x: i32 = 0;
            while (x < self.dimensions[0] - 1) : (x += 1) {
                const idx = @as(usize, @intCast(z * self.dimensions[0] + x));
                self.needs_update[idx] = true;
            }
        }
    }

    // Equivalent to regenerate_mesh
    pub fn regenerate_mesh(self: *Self) !void {
        // Clear current mesh buffers
        self.out_verts.clearRetainingCapacity();
        self.out_uvs.clearRetainingCapacity();
        self.out_uv2s.clearRetainingCapacity();

        // SurfaceTool begin/create_from omitted (assuming fresh generation)

        // Note: Logic for checking new_chunk based on grass/maps is omitted
        // as per instructions to remove color/grass logic.

        try self.generate_terrain_cells();

        if (self.new_chunk) {
            self.new_chunk = false;
        }

        // st.generate_normals() and st.index() and st.commit() would happen here
    }

    fn generate_terrain_cells(self: *Self) !void {
        // dimensions.z and x are size of array, cell loop goes to size - 1
        var z: i32 = 0;
        while (z < self.dimensions[2] - 1) : (z += 1) {
            var x: i32 = 0;
            while (x < self.dimensions[0] - 1) : (x += 1) {
                self.current_cell_coords = .{ .x = x, .y = z };
                const idx = @as(usize, @intCast(z * self.dimensions[0] + x));

                // If geometry did not change, copy already generated geometry
                if (!self.needs_update[idx]) {
                    if (self.cell_geometry[idx]) |geo| {
                        var i: usize = 0;
                        while (i < geo.verts.items.len) : (i += 1) {
                            // Copy to main buffer
                            // st.set_smooth_group(0 if is_floor else -1) - implied by context
                            try self.out_uvs.append(geo.uvs.items[i]);
                            try self.out_uv2s.append(geo.uv2s.items[i]);
                            try self.out_verts.append(geo.verts.items[i]);
                        }
                        continue;
                    }
                }

                // Cell is now being updated
                self.needs_update[idx] = false;

                // Initialize or clear cache entry
                if (self.cell_geometry[idx]) |*geo| {
                    geo.deinit();
                }
                self.cell_geometry[idx] = CellGeoData.init(self.allocator);

                self.r = 0;

                // Get heights of 4 surrounding corners
                self.ay = self.get_height(x, z); // top-left
                self.by = self.get_height(x + 1, z); // top-right
                self.cy = self.get_height(x, z + 1); // bottom-left
                self.dy = self.get_height(x + 1, z + 1); // bottom-right

                // Track edges
                self.ab = self.is_merged(self.ay, self.by);
                self.ac = self.is_merged(self.ay, self.cy);
                self.bd = self.is_merged(self.by, self.dy);
                self.cd = self.is_merged(self.cy, self.dy);

                // Case 0: All edges connected
                if (self.ab and self.bd and self.cd and self.ac) {
                    try self.add_full_floor();
                    continue;
                }

                // Edges clockwise
                self.cell_edges = [4]bool{ self.ab, self.bd, self.cd, self.ac };
                // Points clockwise
                self.point_heights = [4]f32{ self.ay, self.by, self.dy, self.cy };

                var case_found = true;

                // Try rotations 0 to 3
                var i: i32 = 0;
                while (i < 4) : (i += 1) {
                    self.r = i;

                    self.ab = self.cell_edges[@intCast(@mod(self.r, 4))];
                    self.bd = self.cell_edges[@intCast(@mod(self.r + 1, 4))];
                    self.cd = self.cell_edges[@intCast(@mod(self.r + 2, 4))];
                    self.ac = self.cell_edges[@intCast(@mod(self.r + 3, 4))];

                    self.ay = self.point_heights[@intCast(@mod(self.r, 4))];
                    self.by = self.point_heights[@intCast(@mod(self.r + 1, 4))];
                    self.dy = self.point_heights[@intCast(@mod(self.r + 2, 4))];
                    self.cy = self.point_heights[@intCast(@mod(self.r + 3, 4))];

                    case_found = true;

                    // Case 1
                    if (self.is_higher(self.ay, self.by) and self.is_higher(self.ay, self.cy) and self.bd and self.cd) {
                        try self.add_outer_corner(true, true, false, -1);
                    }
                    // Case 2
                    else if (self.is_higher(self.ay, self.cy) and self.is_higher(self.by, self.dy) and self.ab and self.cd) {
                        try self.add_edge(true, true, 0, 1);
                    }
                    // Case 3
                    else if (self.is_higher(self.ay, self.by) and self.is_higher(self.ay, self.cy) and self.is_higher(self.by, self.dy) and self.cd) {
                        try self.add_edge(true, true, 0.5, 1);
                        try self.add_outer_corner(false, true, true, self.by);
                    }
                    // Case 4
                    else if (self.is_higher(self.by, self.ay) and self.is_higher(self.ay, self.cy) and self.is_higher(self.by, self.dy) and self.cd) {
                        try self.add_edge(true, true, 0, 0.5);
                        self.rotate_cell(1);
                        try self.add_outer_corner(false, true, true, self.cy);
                    }
                    // Case 5
                    else if (self.is_lower(self.ay, self.by) and self.is_lower(self.ay, self.cy) and self.is_lower(self.dy, self.by) and self.is_lower(self.dy, self.cy) and self.is_merged(self.by, self.cy)) {
                        try self.add_inner_corner(true, false, false, false, false);
                        try self.add_diagonal_floor(self.by, self.cy, true, true);
                        self.rotate_cell(2);
                        try self.add_inner_corner(true, false, false, false, false);
                    }
                    // Case 5.5
                    else if (self.is_lower(self.ay, self.by) and self.is_lower(self.ay, self.cy) and self.is_lower(self.dy, self.by) and self.is_lower(self.dy, self.cy) and self.is_higher(self.by, self.cy)) {
                        try self.add_inner_corner(true, false, true, false, false);
                        try self.add_diagonal_floor(self.cy, self.cy, true, true);

                        self.rotate_cell(2);
                        try self.add_inner_corner(true, false, true, false, false);

                        self.rotate_cell(-1);
                        try self.add_outer_corner(false, true, false, -1);
                    }
                    // Case 6
                    else if (self.is_lower(self.ay, self.by) and self.is_lower(self.ay, self.cy) and self.bd and self.cd) {
                        try self.add_inner_corner(true, true, false, false, false);
                    }
                    // Case 7
                    else if (self.is_lower(self.ay, self.by) and self.is_lower(self.ay, self.cy) and self.is_higher(self.dy, self.by)
                    and self.is_higher(self.dy, self.cy) and self.is_merged(self.by, self.cy)) {
                        try self.add_inner_corner(true, false, false, false, false);
                        try self.add_diagonal_floor(self.by, self.cy, true, false);
                        self.rotate_cell(2);
                        try self.add_outer_corner(false, true, false, -1);
                    }
                    // Case 8
                    else if (self.is_lower(self.ay, self.by) and self.is_lower(self.ay, self.cy) and self.is_lower(self.dy, self.cy) and self.bd) {
                        try self.add_inner_corner(true, false, true, false, false);
                        self.start_floor();

                        // D corner
                        try self.add_point(1, self.dy, 1, 0, 0, false);
                        try self.add_point(0.5, self.dy, 1, 1, 0, false);
                        try self.add_point(1, (self.by + self.dy) / 2.0, 0.5, 0, 0, false);

                        // B corner
                        try self.add_point(1, self.by, 0, 0, 0, false);
                        try self.add_point(1, (self.by + self.dy) / 2.0, 0.5, 0, 0, false);
                        try self.add_point(0.5, self.by, 0, 0, 1, false);

                        // Center floors
                        try self.add_point(0.5, self.by, 0, 0, 1, false);
                        try self.add_point(1, (self.by + self.dy) / 2.0, 0.5, 0, 0, false);
                        try self.add_point(0, self.by, 0.5, 1, 1, false);

                        try self.add_point(0.5, self.dy, 1, 1, 0, false);
                        try self.add_point(0, self.by, 0.5, 1, 1, false);
                        try self.add_point(1, (self.by + self.dy) / 2.0, 0.5, 0, 0, false);

                        // Walls to upper corner
                        self.start_wall();
                        try self.add_point(0, self.by, 0.5, 0, 0, false);
                        try self.add_point(0.5, self.dy, 1, 0, 0, false); // Assuming normal wall UVs
                        try self.add_point(0, self.cy, 0.5, 0, 0, false);

                        try self.add_point(0.5, self.cy, 1, 0, 0, false);
                        try self.add_point(0, self.cy, 0.5, 0, 0, false);
                        try self.add_point(0.5, self.dy, 1, 0, 0, false);

                        // C upper floor
                        self.start_floor();
                        try self.add_point(0, self.cy, 1, 0, 0, false);
                        try self.add_point(0, self.cy, 0.5, 0, 1, false);
                        try self.add_point(0.5, self.cy, 1, 0, 1, false);
                    }
                    // Case 9
                    else if (self.is_lower(self.ay, self.by) and self.is_lower(self.ay, self.cy) and self.is_lower(self.dy, self.by) and self.cd) {
                        try self.add_inner_corner(true, false, true, false, false);

                        // D corner. C edge connected
                        self.start_floor();
                        try self.add_point(1, self.dy, 1, 0, 0, false);
                        try self.add_point(0.5, (self.dy + self.cy) / 2.0, 1, 0, 0, false);
                        try self.add_point(1, self.dy, 0.5, 0, 0, false);

                        // C corner
                        try self.add_point(0, self.cy, 1, 0, 0, false);
                        try self.add_point(0, self.cy, 0.5, 0, 0, false);
                        try self.add_point(0.5, (self.dy + self.cy) / 2.0, 1, 0, 0, false);

                        // Center floors
                        try self.add_point(0, self.cy, 0.5, 0, 0, false);
                        try self.add_point(0.5, self.cy, 0, 0, 0, false);
                        try self.add_point(0.5, (self.dy + self.cy) / 2.0, 1, 0, 0, false);

                        try self.add_point(1, self.dy, 0.5, 0, 0, false);
                        try self.add_point(0.5, (self.dy + self.cy) / 2.0, 1, 0, 0, false);
                        try self.add_point(0.5, self.cy, 0, 0, 0, false);

                        // Walls to upper corner
                        self.start_wall();
                        try self.add_point(0.5, self.cy, 0, 0, 0, false);
                        try self.add_point(0.5, self.by, 0, 0, 0, false);
                        try self.add_point(1, self.dy, 0.5, 0, 0, false);

                        try self.add_point(1, self.by, 0.5, 0, 0, false);
                        try self.add_point(1, self.dy, 0.5, 0, 0, false);
                        try self.add_point(0.5, self.by, 0, 0, 0, false);

                        // B upper floor
                        self.start_floor();
                        try self.add_point(1, self.by, 0, 0, 0, false);
                        try self.add_point(1, self.by, 0.5, 0, 0, false);
                        try self.add_point(0.5, self.by, 0, 0, 0, false);
                    }
                    // Case 10
                    else if (self.is_lower(self.ay, self.by) and self.is_lower(self.ay, self.cy) and self.is_higher(self.dy, self.cy) and self.bd) {
                        try self.add_inner_corner(true, false, true, true, false);
                        self.rotate_cell(1);
                        try self.add_edge(false, true, 0, 1);
                    }
                    // Case 11
                    else if (self.is_lower(self.ay, self.by) and self.is_lower(self.ay, self.cy) and self.is_higher(self.dy, self.by) and self.cd) {
                        try self.add_inner_corner(true, false, true, false, true);
                        self.rotate_cell(2);
                        try self.add_edge(false, true, 0, 1);
                    }
                    // Case 12
                    else if (self.is_lower(self.ay, self.by) and self.is_lower(self.by, self.dy) and self.is_lower(self.dy, self.cy)
                    and self.is_higher(self.cy, self.ay)) {
                        try self.add_inner_corner(true, false, true, false, true);
                        self.rotate_cell(2);
                        try self.add_edge(false, true, 0, 0.5);
                        self.rotate_cell(1);
                        try self.add_outer_corner(false, true, true, self.cy);
                    }
                    // Case 13
                    else if (self.is_lower(self.ay, self.cy) and self.is_lower(self.cy, self.dy) and self.is_lower(self.dy, self.by)
                    and self.is_higher(self.by, self.ay)) {
                        try self.add_inner_corner(true, false, true, true, false);
                        self.rotate_cell(1);
                        try self.add_edge(false, true, 0.5, 1);
                        try self.add_outer_corner(false, true, true, self.by);
                    }
                    // Case 14
                    else if (self.is_lower(self.ay, self.by) and self.is_lower(self.by, self.cy) and self.is_lower(self.cy, self.dy)) {
                        try self.add_inner_corner(true, false, true, false, true);
                        self.rotate_cell(2);
                        try self.add_edge(false, true, 0.5, 1);
                        try self.add_outer_corner(false, true, true, self.by);
                    }
                    // Case 15
                    else if (self.is_lower(self.ay, self.cy) and self.is_lower(self.cy, self.by) and self.is_lower(self.by, self.dy)) {
                        try self.add_inner_corner(true, false, true, true, false);
                        self.rotate_cell(1);
                        try self.add_edge(false, true, 0, 0.5);
                        self.rotate_cell(1);
                        try self.add_outer_corner(false, true, true, self.cy);
                    }
                    // Case 16
                    else if (self.ab and self.bd and self.cd and self.is_higher(self.ay, self.cy)) {
                        const edge_by = (self.by + self.dy) / 2.0;
                        const edge_dy = (self.by + self.dy) / 2.0;

                        // Upper floor
                        self.start_floor();
                        try self.add_point(0, self.ay, 0, 0, 0, false);
                        try self.add_point(1, self.by, 0, 0, 0, false);
                        try self.add_point(1, edge_by, 0.5, 0, 0, false);

                        try self.add_point(1, edge_by, 0.5, 0, 1, false);
                        try self.add_point(0, self.ay, 0.5, 0, 1, false);
                        try self.add_point(0, self.ay, 0, 0, 0, false);

                        // Wall
                        self.start_wall();
                        try self.add_point(0, self.cy, 0.5, 0, 0, false);
                        try self.add_point(0, self.ay, 0.5, 0, 1, false);
                        try self.add_point(1, edge_dy, 0.5, 1, 0, false);

                        // Lower floor
                        self.start_floor();
                        try self.add_point(0, self.cy, 0.5, 1, 0, false);
                        try self.add_point(1, edge_dy, 0.5, 1, 0, false);
                        try self.add_point(0, self.cy, 1, 0, 0, false);

                        try self.add_point(1, self.dy, 1, 0, 0, false);
                        try self.add_point(0, self.cy, 1, 0, 0, false);
                        try self.add_point(1, edge_dy, 0.5, 0, 0, false);
                    }
                    // Case 17
                    else if (self.ab and self.ac and self.cd and self.is_higher(self.by, self.dy)) {
                        const edge_ay = (self.ay + self.cy) / 2.0;
                        const edge_cy = (self.ay + self.cy) / 2.0;

                        // Upper floor
                        self.start_floor();
                        try self.add_point(0, self.ay, 0, 0, 0, false);
                        try self.add_point(1, self.by, 0, 0, 0, false);
                        try self.add_point(0, edge_ay, 0.5, 0, 0, false);

                        try self.add_point(1, self.by, 0.5, 0, 1, false);
                        try self.add_point(0, edge_ay, 0.5, 0, 1, false);
                        try self.add_point(1, self.by, 0, 0, 0, false);

                        // Wall
                        self.start_wall();
                        try self.add_point(1, self.by, 0.5, 1, 1, false);
                        try self.add_point(1, self.dy, 0.5, 1, 0, false);
                        try self.add_point(0, edge_ay, 0.5, 0, 0, false);

                        // Lower floor
                        self.start_floor();
                        try self.add_point(0, edge_cy, 0.5, 1, 0, false);
                        try self.add_point(1, self.dy, 0.5, 1, 0, false);
                        try self.add_point(1, self.dy, 1, 0, 0, false);

                        try self.add_point(0, self.cy, 1, 0, 0, false);
                        try self.add_point(0, edge_cy, 0.5, 0, 0, false);
                        try self.add_point(1, self.dy, 1, 0, 0, false);
                    } else {
                        case_found = false;
                    }

                    if (case_found) break;
                }

                if (!case_found) {
                    try self.add_full_floor();
                }
            }
        }
    }

    // --- Helper Functions ---

    fn get_height(self: *Self, x: i32, z: i32) f32 {
        const idx = @as(usize, @intCast(z * self.dimensions.x + x));
        return self.height_map[idx];
    }

    fn is_higher(self: *Self, a: f32, b: f32) bool {
        return a - b > self.merge_threshold;
    }

    fn is_lower(self: *Self, a: f32, b: f32) bool {
        return a - b < -self.merge_threshold;
    }

    fn is_merged(self: *Self, a: f32, b: f32) bool {
        return @abs(a - b) < self.merge_threshold;
    }

    fn rotate_cell(self: *Self, rotations: i32) void {
        const r_mod = @mod(self.r + 4 + rotations, 4);
        self.r = @intCast(r_mod);

        self.ab = self.cell_edges[@intCast(@mod(self.r, 4))];
        self.bd = self.cell_edges[@intCast(@mod(self.r + 1, 4))];
        self.cd = self.cell_edges[@intCast(@mod(self.r + 2, 4))];
        self.ac = self.cell_edges[@intCast(@mod(self.r + 3, 4))];

        self.ay = self.point_heights[@intCast(@mod(self.r, 4))];
        self.by = self.point_heights[@intCast(@mod(self.r + 1, 4))];
        self.dy = self.point_heights[@intCast(@mod(self.r + 2, 4))];
        self.cy = self.point_heights[@intCast(@mod(self.r + 3, 4))];
    }

    fn add_point(self: *Self, in_x: f32, in_y: f32, in_z: f32, uv_x: f32, uv_y: f32, diag_midpoint: bool) !void {
        _ = diag_midpoint; // Color logic removed, this arg is unused in geometry-only logic.

        var x = in_x;
        const y = in_y;
        var z = in_z;

        // Apply Rotation
        var i: i32 = 0;
        while (i < self.r) : (i += 1) {
            const temp = x;
            x = 1.0 - z;
            z = temp;
        }

        // UV
        const uv = if (self.floor_mode) vec2{  uv_x, uv_y } else vec2{ 1.0, 1.0 };
        try self.out_uvs.append(uv);

        // Vertex
        const vert = vec3{
            (@as(f32, @floatFromInt(self.current_cell_coords[0])) + x) * self.cell_size.x,
            y,
            (@as(f32, @floatFromInt(self.current_cell_coords[1])) + z) * self.cell_size.y,
        };

        // UV2
        var uv2: vec2 = undefined;
        if (self.floor_mode) {
            uv2 = (vec2{ vert.x, vert.z }).divVec(self.cell_size);
        } else {
            const global_pos = vert.add(self.global_position);
            uv2 = (vec2{ global_pos[0], global_pos[1] }).add(vec2{ global_pos[2], global_pos[1] });
        }
        try self.out_uv2s.append(uv2);
        try self.out_verts.append(vert);

        // Update Cache
        const idx = @as(usize, @intCast(self.current_cell_coords[1] * self.dimensions[0] + self.current_cell_coords[0]));
        if (self.cell_geometry[idx]) |*geo| {
            try geo.verts.append(vert);
            try geo.uvs.append(uv);
            try geo.uv2s.append(uv2);
            try geo.is_floor.append(self.floor_mode);
        }
    }

    fn start_floor(self: *Self) void {
        self.floor_mode = true;
        // set_smooth_group(0) implied
    }

    fn start_wall(self: *Self) void {
        self.floor_mode = false;
        // set_smooth_group(-1) implied
    }

    fn add_full_floor(self: *Self) !void {
        self.start_floor();

        if (self.higher_poly_floors) {
            const ey = (self.ay + self.by + self.cy + self.dy) / 4.0;

            try self.add_point(0, self.ay, 0, 0, 0, false);
            try self.add_point(1, self.by, 0, 0, 0, false);
            try self.add_point(0.5, ey, 0.5, 0, 0, true);

            try self.add_point(1, self.by, 0, 0, 0, false);
            try self.add_point(1, self.dy, 1, 0, 0, false);
            try self.add_point(0.5, ey, 0.5, 0, 0, true);

            try self.add_point(1, self.dy, 1, 0, 0, false);
            try self.add_point(0, self.cy, 1, 0, 0, false);
            try self.add_point(0.5, ey, 0.5, 0, 0, true);

            try self.add_point(0, self.cy, 1, 0, 0, false);
            try self.add_point(0, self.ay, 0, 0, 0, false);
            try self.add_point(0.5, ey, 0.5, 0, 0, true);
        } else {
            try self.add_point(0, self.ay, 0, 0, 0, false);
            try self.add_point(1, self.by, 0, 0, 0, false);
            try self.add_point(0, self.cy, 1, 0, 0, false);

            try self.add_point(1, self.dy, 1, 0, 0, false);
            try self.add_point(0, self.cy, 1, 0, 0, false);
            try self.add_point(1, self.by, 0, 0, 0, false);
        }
    }

    fn add_outer_corner(self: *Self, floor_below: bool, floor_above: bool, flatten_bottom: bool, bottom_height: f32) !void {
        const edge_by = if (flatten_bottom) bottom_height else self.by;
        const edge_cy = if (flatten_bottom) bottom_height else self.cy;

        if (floor_above) {
            self.start_floor();
            try self.add_point(0, self.ay, 0, 0, 0, false);
            try self.add_point(0.5, self.ay, 0, 0, 1, false);
            try self.add_point(0, self.ay, 0.5, 0, 1, false);
        }

        self.start_wall();
        try self.add_point(0, edge_cy, 0.5, 0, 0, false);
        try self.add_point(0, self.ay, 0.5, 0, 1, false);
        try self.add_point(0.5, edge_by, 0, 1, 0, false);

        try self.add_point(0.5, self.ay, 0, 1, 1, false);
        try self.add_point(0.5, edge_by, 0, 1, 0, false);
        try self.add_point(0, self.ay, 0.5, 0, 1, false);

        if (floor_below) {
            self.start_floor();
            try self.add_point(1, self.dy, 1, 0, 0, false);
            try self.add_point(0, self.cy, 1, 0, 0, false);
            try self.add_point(1, self.by, 0, 0, 0, false);

            try self.add_point(0, self.cy, 1, 0, 0, false);
            try self.add_point(0, self.cy, 0.5, 1, 0, false);
            try self.add_point(0.5, self.by, 0, 1, 0, false);

            try self.add_point(1, self.by, 0, 0, 0, false);
            try self.add_point(0, self.cy, 1, 0, 0, false);
            try self.add_point(0.5, self.by, 0, 1, 0, false);
        }
    }

    fn add_edge(self: *Self, floor_below: bool, floor_above: bool, a_x: f32, b_x: f32) !void {
        const edge_ay = if (self.ab) self.ay else @min(self.ay, self.by);
        const edge_by = if (self.ab) self.by else @min(self.ay, self.by);
        const edge_cy = if (self.cd) self.cy else @max(self.cy, self.dy);
        const edge_dy = if (self.cd) self.dy else @max(self.cy, self.dy);

        if (floor_above) {
            self.start_floor();
            try self.add_point(a_x, edge_ay, 0, if (a_x > 0) 1.0 else 0.0, 0, false);
            try self.add_point(b_x, edge_by, 0, if (b_x < 1) 1.0 else 0.0, 0, false);

            const uv_y_1 = if (b_x < 1) -1.0 else if (a_x > 0) 1.0 else 0.0;
            try self.add_point(0, edge_ay, 0.5, uv_y_1, 1, false);

            const uv_y_2 = if (a_x > 0) -1.0 else if (b_x < 1) 1.0 else 0.0;
            try self.add_point(1, edge_by, 0.5, uv_y_2, 1, false);
            try self.add_point(0, edge_ay, 0.5, uv_y_1, 1, false);
            try self.add_point(b_x, edge_by, 0, if (b_x < 1) 1.0 else 0.0, 0, false);
        }

        self.start_wall();
        try self.add_point(0, edge_cy, 0.5, 0, 0, false);
        try self.add_point(0, edge_ay, 0.5, 0, 1, false);
        try self.add_point(1, edge_dy, 0.5, 1, 0, false);

        try self.add_point(1, edge_by, 0.5, 1, 1, false);
        try self.add_point(1, edge_dy, 0.5, 1, 0, false);
        try self.add_point(0, edge_ay, 0.5, 0, 1, false);

        if (floor_below) {
            self.start_floor();
            try self.add_point(0, self.cy, 0.5, 1, 0, false);
            try self.add_point(1, self.dy, 0.5, 1, 0, false);
            try self.add_point(0, self.cy, 1, 0, 0, false);

            try self.add_point(1, self.dy, 1, 0, 0, false);
            try self.add_point(0, self.cy, 1, 0, 0, false);
            try self.add_point(1, self.dy, 0.5, 1, 0, false);
        }
    }

    fn add_inner_corner(self: *Self, lower_floor: bool, full_upper_floor: bool, flatten: bool, bd_floor: bool, cd_floor: bool) !void {
        const corner_by = if (flatten) @min(self.by, self.cy) else self.by;
        const corner_cy = if (flatten) @min(self.by, self.cy) else self.cy;

        if (lower_floor) {
            self.start_floor();
            try self.add_point(0, self.ay, 0, 0, 0, false);
            try self.add_point(0.5, self.ay, 0, 1, 0, false);
            try self.add_point(0, self.ay, 0.5, 1, 0, false);
        }

        self.start_wall();
        try self.add_point(0, self.ay, 0.5, 1, 0, false);
        try self.add_point(0.5, self.ay, 0, 0, 0, false);
        try self.add_point(0, corner_cy, 0.5, 1, 1, false);

        try self.add_point(0.5, corner_by, 0, 0, 1, false);
        try self.add_point(0, corner_cy, 0.5, 1, 1, false);
        try self.add_point(0.5, self.ay, 0, 0, 0, false);

        self.start_floor();
        if (full_upper_floor) {
            try self.add_point(1, self.dy, 1, 0, 0, false);
            try self.add_point(0, corner_cy, 1, 0, 0, false);
            try self.add_point(1, corner_by, 0, 0, 0, false);

            try self.add_point(0, corner_cy, 1, 0, 0, false);
            try self.add_point(0, corner_cy, 0.5, 0, 1, false);
            try self.add_point(0.5, corner_by, 0, 0, 1, false);

            try self.add_point(1, corner_by, 0, 0, 0, false);
            try self.add_point(0, corner_cy, 1, 0, 0, false);
            try self.add_point(0.5, corner_by, 0, 0, 1, false);
        }

        if (cd_floor) {
            try self.add_point(1, self.by, 0, 0, 0, false);
            try self.add_point(0, self.by, 0.5, 1, 1, false);
            try self.add_point(0.5, self.by, 0, 0, 1, false);

            try self.add_point(1, self.by, 0, 0, 0, false);
            try self.add_point(1, self.by, 0.5, 1, -1, false);
            try self.add_point(0, self.by, 0.5, 1, 1, false);
        }

        if (bd_floor) {
            try self.add_point(0, self.cy, 0.5, 0, 1, false);
            try self.add_point(0.5, self.cy, 0, 1, 1, false);
            try self.add_point(0, self.cy, 1, 0, 0, false);

            try self.add_point(0.5, self.cy, 1, 1, -1, false);
            try self.add_point(0, self.cy, 1, 0, 0, false);
            try self.add_point(0.5, self.cy, 0, 1, 1, false);
        }
    }

    fn add_diagonal_floor(self: *Self, b_y: f32, c_y: f32, a_cliff: bool, d_cliff: bool) !void {
        self.start_floor();

        try self.add_point(1, b_y, 0, 0, 0, false);
        try self.add_point(0, c_y, 1, 0, 0, false);
        try self.add_point(0.5, b_y, 0, if (a_cliff) 0.0 else 1.0, if (a_cliff) 1.0 else 0.0, false);

        try self.add_point(0, c_y, 1, 0, 0, false);
        try self.add_point(0, c_y, 0.5, if (a_cliff) 0.0 else 1.0, if (a_cliff) 1.0 else 0.0, false);
        try self.add_point(0.5, b_y, 0, if (a_cliff) 0.0 else 1.0, if (a_cliff) 1.0 else 0.0, false);

        try self.add_point(1, b_y, 0, 0, 0, false);
        try self.add_point(1, b_y, 0.5, if (d_cliff) 0.0 else 1.0, if (d_cliff) 1.0 else 0.0, false);
        try self.add_point(0, c_y, 1, 0, 0, false);

        try self.add_point(0, c_y, 1, 0, 0, false);
        try self.add_point(1, b_y, 0.5, if (d_cliff) 0.0 else 1.0, if (d_cliff) 1.0 else 0.0, false);
        try self.add_point(0.5, c_y, 1, if (d_cliff) 0.0 else 1.0, if (d_cliff) 1.0 else 0.0, false);
    }
};
